### ISSUE TITLE
`input-text` entity not updated when pressing `enter`. How to update?

### ISSUE THREAD

**Issue by haakonstorm** [gadgetchnnel/lovelace-text-input-row#2]
Thanks for this component, I'm testing it out to try and get an Amazon Echo notification based on string input via `lovelace-text-input-row`.

Everything works, the message is announced to the correctly `input-select` chosen Echo.

The `input-select` is prefilled with the text `message`. When I change this text and press enter, then click the button that kicks of the script, invariably the old text `message` is announced. The state/string of my `input-select` entity is never updated. How is this designed to work? 

Relevant background:
- Latest HA running on `RPi4-4GB` HASSIO
- Your repo added via HACS

`ui-resources.yaml`

```
- url: /hacsfiles/lovelace-text-input-row/lovelace-text-input-row.js 
  type: js
```

(also tried with `type: module`; documentation from HACS state `module` but documentation from this repo states `js`(!))

## my HA frontend view:

```
- title: '4'
  badges: []
  icon: 'mdi:ear-hearing'
  type: vertical-stack
  cards:
    - type: entities
      entities:
        - entity: input_text.alexattstext
          type: 'custom:text-input-row'
        - entity: input_select.alexattsselect
        - type: call-service
          name: ' '
          icon: 'mdi:voice'
          action_name: Speak
          service: 
            script.sayit
```

## definiton of `input_text` and `input_select`

In each of their respective sections:
```
alexattsselect:
  name: Alexa Speak
  options:
    - media_player.echo_bedroom
    - media_player.echo_laboratory
    - media_player.echo_workshop
    - media_player.echo_kitchen
    - media_player.echo_elisabeth
    - media_player.echo_auto
    - media_player.echo_mini
    - media_player.upstairs
    - media_player.bedroom
    - media_player.sonos_upstairs
    - media_player.sonos_bedroom
    - media_player.the_little_one
```

```
alexattstxt:
  name: AlexaTTStext
```

## Script

```
sayit:
  alias: 'Say it'
  sequence:
    - service: notify.alexa_media
      data_template:
        target: "{{ states.input_select.alexattsselect.state }}"
        data:
          type: announce
          method: speak
        message: '
          {{ states("input_text.alexattstxt") }}'
```

How to get it to work?
