### ISSUE TITLE
Error after Update HA to 2023.11.0

### ISSUE THREAD

**Issue by GerdRuetten** [gadgetchnnel/lovelace-text-input-row#7]
Hi,

after Update HA core to 2023.11.0 the input-row don't show

My Card-Code:
```
type: entities
entities:
  - entity: input_text.essen_fertig_xx
    type: custom:text-input-row
    name: Essen in

```

No error in the HA log.

Restore to HA core 2023.10.x shows the input-row
